image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- go
environment:
  site: macintoshpie.srht.site
  mydomain: tedsummer.com
tasks:
- package: |
    cd ${site}
    go run ./cmd/build
    cd ./build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d tedsummer.com -p HTTPS site.tar.gz
    hut pages publish -d tedsummer.com -p GEMINI site.tar.gz
