image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- go
environment:
  site: macintoshpie.srht.site
  top_level_domain: tedsummer.com
tasks:
- package: |
    cd ${site}
    ./scripts/package.sh
- upload: |
    cd ${site}
    ./scripts/publish.sh ${top_level_domain}
