image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: macintoshpie.srht.site
tasks:
- package: |
    cd ${site}/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d $site -p HTTPS site.tar.gz
    hut pages publish -d $site -p GEMINI site.tar.gz
